### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by bagoferasers** [JeremyARandall/Paw-World#2]
# Project Structure Issues with LINKED Milestones
Create new issues and link different milestones in the following:
- [x] 18FEB2023 "Individual exploration of technologies"
- [x] 04MAR2023 "Foundational programming"
- [x] 14MAR2023 "Implementation of features"
- [x] 04APR2023 "Login page"
- [x] 07APR2023 "Add-on features"
- [x] 15APR2023 "Final proposal"
- [x] 17APR2023 "Presentation complete"
